
List<CountryFlag> countryName =[
  CountryFlag(countryName:"Afghanistan",flag:'https://www.countries-ofthe-world.com/flags-normal/flag-of-Afghanistan.png'),
  CountryFlag(countryName: "Albania",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Albania.png" ),
  CountryFlag(countryName: "Algeria",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Algeria.png" ),
  CountryFlag(countryName:"Andorra",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Andorra.png"),
  CountryFlag(countryName:"Angola",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Angola.png"),
  CountryFlag(countryName:"Antigua and Barbuda",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Antigua.png" ),
  CountryFlag(countryName:"Argentina",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Argentina.png"),
  CountryFlag(countryName:"Armenia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Armenia.png" ),
  CountryFlag(countryName:"Australia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Australia.png" ),
  CountryFlag(countryName:"Austria",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Austria.png" ),
  CountryFlag(countryName:"Azerbaijan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Azerbaijan.png" ),
  CountryFlag(countryName:"Bahamas",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Bahamas.png" ),
  CountryFlag(countryName:"Bahrain",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Bahrain.png" ),
  CountryFlag(countryName:"Bangladesh",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Bangladesh.png" ),
  CountryFlag(countryName: "Barbados",flag: 'https://www.countries-ofthe-world.com/flags-normal/flag-of-Barbados.png'),
  CountryFlag(countryName: "Belarus",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Belarus.png"),
  CountryFlag(countryName:"Belgium",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Belize.png" ),
  CountryFlag(countryName:"Belize",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Belize.png" ),
  CountryFlag(countryName:"Benin",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Benin.png" ),
  CountryFlag(countryName:"Bhutan",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Bhutan.png"  ),
  CountryFlag(countryName:"Bolivia",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Bolivia.png"),
  CountryFlag(countryName:"Bosnia and Herzegovina",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Bosnia-Herzegovina.png" ),
  CountryFlag(countryName:"Botswana",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Botswana.png"),
  CountryFlag(countryName: "Brazil",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Brazil.png"),
  CountryFlag(countryName: "Brunei",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Brunei.png"),
  CountryFlag(countryName:"Bulgaria",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Bulgaria.png" ),
  CountryFlag(countryName: "Burkina Faso",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Burkina-Faso.png"),
  CountryFlag(countryName: "Burma",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Myanmar.png" ),
  CountryFlag(countryName: "Burundi",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Burundi.png"),
  CountryFlag(countryName:"Cabo Verde",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Cabo-Verde.png" ),
  CountryFlag(countryName:"Cambodia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Cambodia.png" ),
  CountryFlag(countryName:"Cameroon",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Cameroon.png" ),
  CountryFlag(countryName:"Canada",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Canada.png" ),
  CountryFlag(countryName:"Central African Republic",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Central-African-Republic.png" ),
  CountryFlag(countryName:"Chad",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Chad.png"  ),
  CountryFlag(countryName:"Chile",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Chile.png"),
  CountryFlag(countryName: "China",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-China.png"),
  CountryFlag(countryName:"Colombia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Colombia.png" ),
  CountryFlag(countryName:"Comoros",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Comoros.png" ),
  CountryFlag(countryName:"Congo (Brazzaville)",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Congo-Democratic-Republic-of.png" ),
  CountryFlag(countryName:"Congo (Kinshasa)",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Congo.png" ),
  CountryFlag(countryName:"Costa Rica",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Costa-Rica.png"),
  CountryFlag(countryName:"Cote d'Ivoire",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Cote-d-Ivoire.png" ),
  CountryFlag(countryName:"Croatia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Costa-Rica.png" ),
  CountryFlag(countryName:"Cuba",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Cuba.png" ),
  CountryFlag(countryName:"Cyprus",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Cyprus.png" ),
  CountryFlag(countryName:"Czechia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Czech-Republic.png"),
  CountryFlag(countryName:"Denmark",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Denmark.png" ),
  CountryFlag(countryName:"Diamond Princess",flag: "null" ),
  CountryFlag(countryName:"Djibouti",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Djibouti.png" ),
  CountryFlag(countryName:"Dominica",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Dominica.png" ),
  CountryFlag(countryName:"Dominican Republic",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Dominican-Republic.png" ),
  CountryFlag(countryName:"Ecuador",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Ecuador.png" ),
  CountryFlag(countryName:"Egypt",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Egypt.png"  ),
  CountryFlag(countryName: "El Salvador",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-El-Salvador.png"),
  CountryFlag(countryName: "Equatorial Guinea",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Equatorial-Guinea.png"),
  CountryFlag(countryName:"Eritrea",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Eritrea.png"  ),
  CountryFlag(countryName:"Estonia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Estonia.png" ),
  CountryFlag(countryName:"Eswatini",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Eswatini.png" ),
  CountryFlag(countryName:"Ethiopia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Ethiopia.png" ),
  CountryFlag(countryName:"Fiji",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Fiji.png" ),
  CountryFlag(countryName:"Finland",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Finland.png" ),
  CountryFlag(countryName:"France",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-France.png"),
  CountryFlag(countryName:"Gabon",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Georgia.png" ),
  CountryFlag(countryName:"Gambia",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Gambia.png" ),
  CountryFlag(countryName:"Georgia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Georgia.png" ),
  CountryFlag(countryName:"Germany",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Germany.png"),
  CountryFlag(countryName:"Ghana",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Ghana.png" ),
  CountryFlag(countryName:"Greece",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Greece.png" ),
  CountryFlag(countryName:"Grenada",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Grenada.png" ),
  CountryFlag(countryName:"Guatemala",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Guatemala.png" ),
  CountryFlag(countryName:"Guinea",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Guinea.png" ),
  CountryFlag(countryName:"Guinea-Bissau",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Guinea-Bissau.png" ),
  CountryFlag(countryName:"Guyana",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Guyana.png" ),
  CountryFlag(countryName:"Haiti",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Haiti.png" ),
  CountryFlag(countryName: "Holy See",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Vatican-City.png"),
  CountryFlag(countryName:"Honduras",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Honduras.png" ),
  CountryFlag(countryName:"Hungary", flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Hungary.png"),
  CountryFlag(countryName: "Iceland",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Iceland.png"),
  CountryFlag(countryName: "India",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-India.png"),
  CountryFlag(countryName:"Indonesia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Indonesia.png" ),
  CountryFlag(countryName:"Iran",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Iran.png" ),
  CountryFlag(countryName:"Iraq",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Iraq.png" ),
  CountryFlag(countryName:"Ireland",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Ireland.png" ),
  CountryFlag(countryName:"Israel",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Israel.png" ),
  CountryFlag(countryName:"Italy",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Italy.png" ),
  CountryFlag(countryName:"Jamaica",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Jamaica.png" ),
  CountryFlag(countryName:"Japan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Japan.png" ),
  CountryFlag(countryName:"Jordan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Jordan.png" ),
  CountryFlag(countryName:"Kazakhstan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Kazakhstan.png" ),
  CountryFlag(countryName:"Kenya",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Kenya.png" ),
  CountryFlag(countryName:"Korea, South",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Korea-South.png" ),
  CountryFlag(countryName:"Kosovo",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Kosovo.png"  ),
  CountryFlag(countryName:"Kuwait",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Kuwait.png" ),
  CountryFlag(countryName:"Kyrgyzstan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Kyrgyzstan.png" ),
  CountryFlag(countryName:"Laos",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Laos.png"),
  CountryFlag(countryName:"Latvia",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Latvia.png"  ),
  CountryFlag(countryName:"Lebanon",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Lebanon.png" ),
  CountryFlag(countryName:"Lesotho",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Lesotho.png" ),
  CountryFlag(countryName:"Liberia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Liberia.png" ),
  CountryFlag(countryName: "Libya",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Libya.png"),
  CountryFlag(countryName:"Liechtenstein",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Liechtenstein.png" ),
  CountryFlag(countryName: "Lithuania",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Lithuania.png"),
  CountryFlag(countryName:"Luxembourg",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Luxembourg.png" ),
  CountryFlag(countryName:"MS Zaandam",flag: 'null'),
  CountryFlag(countryName:"Madagascar",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Madagascar.png"  ),
  CountryFlag(countryName: "Malawi",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Malawi.png"),
  CountryFlag(countryName:"Malaysia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Malaysia.png" ),
  CountryFlag(countryName: "Maldives",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Maldives.png"),
  CountryFlag(countryName:"Mali",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mali.png" ),
  CountryFlag(countryName:"Malta",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Malta.png" ),
  CountryFlag(countryName:"Mauritania",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mauritania.png" ),
  CountryFlag(countryName:"Mauritius",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mauritius.png" ),
  CountryFlag(countryName:"Mexico",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Mexico.png"  ),
  CountryFlag(countryName:"Moldova",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Moldova.png" ),
  CountryFlag(countryName:"Monaco",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Monaco.png" ),
  CountryFlag(countryName: "Mongolia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mongolia.png"),
  CountryFlag(countryName:"Montenegro",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Montenegro.png" ),
  CountryFlag(countryName: "Morocco",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Morocco.png"),
  CountryFlag(countryName:"Mozambique",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Mozambique.png" ),
  CountryFlag(countryName:"Namibia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Namibia.png" ),
  CountryFlag(countryName: "Nepal",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Nepal.png"),
  CountryFlag(countryName: "Netherlands", flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-New-Zealand.png"),
  CountryFlag(countryName:"New Zealand",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-New-Zealand.png" ),
  CountryFlag(countryName:"Nicaragua", flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Nicaragua.png"),
  CountryFlag(countryName:"Niger",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Niger.png" ),
  CountryFlag(countryName:"Nigeria",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Nigeria.png" ),
  CountryFlag(countryName:"North Macedonia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-North-Macedonia.png" ),
  CountryFlag(countryName: "Norway",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Norway.png"),
  CountryFlag(countryName: "Oman",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Oman.png"),
  CountryFlag(countryName:"Pakistan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Pakistan.png" ),
  CountryFlag(countryName:"Panama",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Panama.png" ),
  CountryFlag(countryName: "Papua New Guinea", flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Papua-New-Guinea.png"),
  CountryFlag(countryName:"Paraguay",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Paraguay.png" ),
  CountryFlag(countryName: "Peru",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Peru.png"),
  CountryFlag(countryName:"Philippines",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Philippines.png" ),
  CountryFlag(countryName: "Poland",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Poland.png"),
  CountryFlag(countryName:"Portugal",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Portugal.png" ),
  CountryFlag(countryName:"Qatar",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Qatar.png" ),
  CountryFlag(countryName:"Romania",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Romania.png" ),
  CountryFlag(countryName:"Russia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Russia.png" ),
  CountryFlag(countryName:"Rwanda",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Rwanda.png" ),
  CountryFlag(countryName:"Saint Kitts and Nevis",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-St-Kitts-Nevis.png" ),
  CountryFlag(countryName:"Saint Lucia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-St-Lucia.png" ),
  CountryFlag(countryName:"Saint Vincent and the Grenadines",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-St-Vincent-the-Grenadines.png" ),
  CountryFlag(countryName:"San Marino",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-San-Marino.png" ),
  CountryFlag(countryName:"Sao Tome and Principe",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-St-Vincent-the-Grenadines.png" ),
  CountryFlag(countryName:"Saudi Arabia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Saudi-Arabia.png" ),
  CountryFlag(countryName: "Senegal",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Senegal.png"),
  CountryFlag(countryName:"Serbia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Serbia.png" ),
  CountryFlag(countryName:"Seychelles",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Seychelles.png" ),
  CountryFlag(countryName:"Sierra Leone",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Sierra-Leone.png" ),
  CountryFlag(countryName:"Singapore",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Singapore.png" ),
  CountryFlag(countryName: "Slovakia", flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Slovakia.png" ),
  CountryFlag(countryName:"Slovenia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Slovenia.png" ),
  CountryFlag(countryName: "Somalia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Somalia.png"),
  CountryFlag(countryName: "South Africa",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-South-Africa.png"),
  CountryFlag(countryName: "South Sudan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-South-Sudan.png"),
  CountryFlag(countryName:"Spain",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Spain.png" ),
  CountryFlag(countryName:"Sri Lanka",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Sri-Lanka.png"  ),
  CountryFlag(countryName:"Sudan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Sudan.png" ),
  CountryFlag(countryName:"Suriname",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Suriname.png" ),
  CountryFlag(countryName:"Sweden",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Sweden.png" ),
  CountryFlag(countryName:"Switzerland",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Switzerland.png"  ),
  CountryFlag(countryName:"Syria",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Syria.png" ),
  CountryFlag(countryName:"Taiwan*",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Taiwan.png" ),
  CountryFlag(countryName:"Tajikistan",flag:"https://www.countries-ofthe-world.com/flags-normal/flag-of-Tajikistan.png"  ),
  CountryFlag(countryName:"Tanzania",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Tanzania.png" ),
  CountryFlag(countryName:"Thailand",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Thailand.png" ),
  CountryFlag(countryName:"Timor-Leste",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Timor-Leste.png" ),
  CountryFlag(countryName:"Togo",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Togo.png" ),
  CountryFlag(countryName:"Trinidad and Tobago",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Trinidad-and-Tobago.png" ),
  CountryFlag(countryName:"Tunisia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Tunisia.png" ),
  CountryFlag(countryName:"Turkey",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Turkey.png" ),
  CountryFlag(countryName:"US",flag: "null" ),
  CountryFlag(countryName:"Uganda",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Uganda.png"),
  CountryFlag(countryName:"Ukraine",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Ukraine.png" ),
  CountryFlag(countryName:"United Arab Emirates",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-United-Arab-Emirates.png"),
  CountryFlag(countryName:"United Kingdom",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-United-Kingdom.png" ),
  CountryFlag(countryName: "Uruguay",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Uruguay.png"),
  CountryFlag(countryName: "Uzbekistan",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Uzbekistan.png"),
  CountryFlag(countryName:"Venezuela",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Venezuela.png" ),
  CountryFlag(countryName:"Vietnam",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Vietnam.png" ),
  CountryFlag(countryName:"West Bank and Gaza",flag: "null" ),
  CountryFlag(countryName:"Western Sahara",flag: "null" ),
  CountryFlag(countryName:"Yemen",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Yemen.png" ),
  CountryFlag(countryName:"Zambia",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Zambia.png" ),
  CountryFlag(countryName:"Zimbabwe",flag: "https://www.countries-ofthe-world.com/flags-normal/flag-of-Zimbabwe.png" )
];

class CountryFlag{
  String countryName;
  String flag;
  CountryFlag({this.countryName, this.flag});
}


